package version_test

import (
	"strings"
	"testing"

	"al.essio.dev/cmd/mkdmg/internal/version"
)

func TestVersionNotEmpty(t *testing.T) {
	if version.Version == "" {
		t.Error("Version should not be empty")
	}
}

func TestVersionFormat(t *testing.T) {
	// Version should be a non-empty string
	if len(version.Version) == 0 {
		t.Fatal("Version length is 0")
	}

	// Trim any whitespace
	trimmed := strings.TrimSpace(version.Version)
	if len(trimmed) == 0 {
		t.Error("Version contains only whitespace")
	}
}

func TestVersionContainsExpectedPattern(t *testing.T) {
	// Version should contain either a version number (like v1.2.3)
	// or UNKNOWN (for development builds)
	if !strings.Contains(version.Version, "UNKNOWN") &&
		!strings.Contains(version.Version, "v") &&
		!strings.Contains(version.Version, ".") {
		t.Logf("Warning: Version '%s' doesn't match expected patterns (v*.*.* or UNKNOWN)", version.Version)
	}
}

func TestVersionIsReadableString(t *testing.T) {
	// Ensure that the version is valid UTF-8 and printable
	if !strings.ContainsAny(version.Version, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.-") {
		t.Errorf("Version '%s' doesn't contain expected characters", version.Version)
	}
}

func TestVersionEmbedded(t *testing.T) {
	// This test verifies that the version is properly embedded from version.txt
	// In a real scenario, the version would be generated by the build process
	// For now, we just verify it's not the zero value
	if version.Version == "" {
		t.Error("Version appears to not be properly embedded from version.txt")
	}
}

func TestVersionConsistency(t *testing.T) {
	// Call the Version variable multiple times to ensure it's consistent
	v1 := version.Version
	v2 := version.Version
	v3 := version.Version

	if v1 != v2 || v2 != v3 {
		t.Errorf("Version is not consistent: v1=%s, v2=%s, v3=%s", v1, v2, v3)
	}
}

func TestVersionNoLeadingTrailingWhitespace(t *testing.T) {
	trimmed := strings.TrimSpace(version.Version)
	if len(trimmed) == 0 {
		t.Error("Version is empty or only whitespace")
	}
	// Note: version.txt may have a trailing newline from the embed, which is acceptable
	// We just verify there's actual content when trimmed
}

func TestVersionDefault(t *testing.T) {
	// The default version.txt contains "v0.0.0-UNKNOWN"
	// This test checks if we're running with the default or a generated version
	if strings.Contains(version.Version, "UNKNOWN") {
		t.Logf("Running with default/development version: %s", version.Version)
	} else {
		t.Logf("Running with generated version: %s", version.Version)
	}
}
